/* The following code was generated by JFlex 1.4.3 on 9/03/18 10:58 PM */

package Gramaticas.CJS;
import Errores.ListaErrores;
import java_cup.runtime.Symbol;
import Errores.ER;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 9/03/18 10:58 PM from the specification file
 * <tt>lexicoCJS.jflex</tt>
 */
public class AnalisisLex_CJS implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\57\1\4\1\0\2\57\22\0\1\57\1\43\1\11\2\0"+
    "\1\44\1\36\1\1\1\53\1\54\1\3\1\46\1\51\1\47\1\10"+
    "\1\2\12\5\1\52\1\50\1\41\1\40\1\42\2\0\1\26\1\24"+
    "\1\27\1\12\1\17\1\32\2\6\1\13\1\31\1\6\1\21\1\14"+
    "\1\22\1\23\1\33\1\35\1\25\1\16\1\20\1\30\1\15\1\6"+
    "\1\34\2\6\3\0\1\45\1\7\1\0\1\26\1\24\1\27\1\12"+
    "\1\17\1\32\2\6\1\13\1\31\1\6\1\21\1\14\1\22\1\23"+
    "\1\33\1\35\1\25\1\16\1\20\1\30\1\15\1\6\1\34\2\6"+
    "\1\55\1\37\1\56\123\0\1\6\37\0\1\6\uff0e\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\13\7\2\1\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\1\26\1\27\1\30\2\0\1\31\2\0\7\7\1\32"+
    "\12\7\1\33\1\34\1\35\1\36\1\37\1\40\1\41"+
    "\1\42\1\0\1\31\1\43\1\44\25\7\3\0\1\45"+
    "\7\7\1\46\11\7\1\47\1\7\1\50\2\51\11\7"+
    "\1\52\23\7\1\53\1\7\1\54\1\7\1\55\1\56"+
    "\3\7\1\57\4\7\1\60\2\7\1\61\1\7\1\62"+
    "\1\63\4\7\1\64\1\7\1\65\4\7\1\66\1\67"+
    "\1\7\1\70\1\71\1\72";

  private static int [] zzUnpackAction() {
    int [] result = new int[187];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\60\0\140\0\60\0\60\0\220\0\300\0\360"+
    "\0\60\0\u0120\0\u0150\0\u0180\0\u01b0\0\u01e0\0\u0210\0\u0240"+
    "\0\u0270\0\u02a0\0\u02d0\0\u0300\0\u0330\0\u0360\0\u0390\0\u03c0"+
    "\0\u03f0\0\u0420\0\u0450\0\60\0\60\0\u0480\0\u04b0\0\60"+
    "\0\60\0\60\0\60\0\60\0\60\0\60\0\u04e0\0\u0510"+
    "\0\60\0\u0540\0\u0570\0\u05a0\0\u05d0\0\u0600\0\u0630\0\u0660"+
    "\0\u0690\0\u06c0\0\u06f0\0\u0720\0\u0750\0\u0780\0\u07b0\0\u07e0"+
    "\0\u0810\0\u0840\0\u0870\0\u08a0\0\u08d0\0\60\0\60\0\60"+
    "\0\60\0\60\0\60\0\60\0\60\0\u0900\0\u0930\0\u0540"+
    "\0\60\0\u0960\0\u0990\0\u09c0\0\u09f0\0\u0a20\0\u0a50\0\u0a80"+
    "\0\u0ab0\0\u0ae0\0\u0b10\0\u0b40\0\u0b70\0\u0ba0\0\u0bd0\0\u0c00"+
    "\0\u0c30\0\u0c60\0\u0c90\0\u0cc0\0\u0cf0\0\u0d20\0\u0d50\0\u0930"+
    "\0\u0d80\0\360\0\u0db0\0\u0de0\0\u0e10\0\u0e40\0\u0e70\0\u0ea0"+
    "\0\u0ed0\0\360\0\u0f00\0\u0f30\0\u0f60\0\u0f90\0\u0fc0\0\u0ff0"+
    "\0\u1020\0\u1050\0\u1080\0\360\0\u10b0\0\360\0\u0900\0\u0930"+
    "\0\u10e0\0\u1110\0\u1140\0\u1170\0\u11a0\0\u11d0\0\u1200\0\u1230"+
    "\0\u1260\0\360\0\u1290\0\u12c0\0\u12f0\0\u1320\0\u1350\0\u1380"+
    "\0\u13b0\0\u13e0\0\u1410\0\u1440\0\u1470\0\u14a0\0\u14d0\0\u1500"+
    "\0\u1530\0\u1560\0\u1590\0\u15c0\0\u15f0\0\360\0\u1620\0\360"+
    "\0\u1650\0\360\0\360\0\u1680\0\u16b0\0\u16e0\0\360\0\u1710"+
    "\0\u1740\0\u1770\0\u17a0\0\360\0\u17d0\0\u1800\0\360\0\u1830"+
    "\0\360\0\360\0\u1860\0\u1890\0\u18c0\0\u18f0\0\360\0\u1920"+
    "\0\360\0\u1950\0\u1980\0\u19b0\0\u19e0\0\360\0\360\0\u1a10"+
    "\0\360\0\360\0\360";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[187];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\2"+
    "\1\11\1\12\1\13\1\14\1\15\1\10\1\16\2\10"+
    "\1\17\1\10\1\20\1\10\1\21\1\22\1\23\2\10"+
    "\1\24\1\25\2\10\1\26\1\27\1\30\1\31\1\32"+
    "\1\33\1\34\1\35\1\36\1\37\1\40\1\41\1\42"+
    "\1\43\1\44\1\45\1\46\1\6\60\0\2\47\1\50"+
    "\1\47\1\51\53\47\4\0\1\6\52\0\1\6\5\0"+
    "\1\7\2\0\1\52\54\0\3\10\2\0\24\10\22\0"+
    "\4\53\1\0\53\53\5\0\3\10\2\0\1\10\1\54"+
    "\3\10\1\55\3\10\1\56\12\10\27\0\3\10\2\0"+
    "\2\10\1\57\21\10\27\0\3\10\2\0\1\10\1\60"+
    "\3\10\1\61\3\10\1\62\12\10\27\0\3\10\2\0"+
    "\1\10\1\63\3\10\1\64\16\10\27\0\3\10\2\0"+
    "\1\10\1\65\22\10\27\0\3\10\2\0\12\10\1\66"+
    "\11\10\27\0\3\10\2\0\5\10\1\67\16\10\27\0"+
    "\3\10\2\0\6\10\1\70\15\10\27\0\3\10\2\0"+
    "\7\10\1\71\1\10\1\72\2\10\1\73\7\10\27\0"+
    "\3\10\2\0\16\10\1\74\5\10\27\0\3\10\2\0"+
    "\14\10\1\75\7\10\60\0\1\76\60\0\1\77\60\0"+
    "\1\100\57\0\1\101\57\0\1\102\57\0\1\103\65\0"+
    "\1\104\60\0\1\105\10\0\4\47\1\51\53\47\3\106"+
    "\1\47\1\107\53\106\5\0\1\110\52\0\11\53\1\111"+
    "\46\53\5\0\3\10\2\0\2\10\1\112\21\10\27\0"+
    "\3\10\2\0\6\10\1\113\11\10\1\114\3\10\27\0"+
    "\3\10\2\0\15\10\1\115\6\10\27\0\3\10\2\0"+
    "\21\10\1\116\2\10\27\0\3\10\2\0\5\10\1\117"+
    "\16\10\27\0\3\10\2\0\10\10\1\120\13\10\27\0"+
    "\3\10\2\0\1\121\23\10\27\0\3\10\2\0\10\10"+
    "\1\122\13\10\27\0\3\10\2\0\6\10\1\123\1\124"+
    "\14\10\27\0\3\10\2\0\4\10\1\125\17\10\27\0"+
    "\3\10\2\0\4\10\1\126\1\10\1\127\15\10\27\0"+
    "\3\10\2\0\6\10\1\130\15\10\27\0\3\10\2\0"+
    "\5\10\1\131\16\10\27\0\3\10\2\0\1\10\1\132"+
    "\22\10\27\0\3\10\2\0\10\10\1\133\13\10\27\0"+
    "\3\10\2\0\4\10\1\134\17\10\27\0\3\10\2\0"+
    "\10\10\1\135\13\10\27\0\3\10\2\0\13\10\1\136"+
    "\10\10\22\0\2\106\1\137\1\47\1\107\53\106\2\140"+
    "\1\141\1\0\54\140\5\0\3\10\2\0\3\10\1\142"+
    "\20\10\27\0\3\10\2\0\5\10\1\143\16\10\27\0"+
    "\3\10\2\0\5\10\1\144\16\10\27\0\3\10\2\0"+
    "\16\10\1\145\5\10\27\0\3\10\2\0\13\10\1\146"+
    "\10\10\27\0\3\10\2\0\10\10\1\147\13\10\27\0"+
    "\3\10\2\0\4\10\1\150\17\10\27\0\3\10\2\0"+
    "\1\10\1\151\22\10\27\0\3\10\2\0\11\10\1\152"+
    "\12\10\27\0\3\10\2\0\5\10\1\153\16\10\27\0"+
    "\3\10\2\0\5\10\1\154\16\10\27\0\3\10\2\0"+
    "\6\10\1\155\15\10\27\0\3\10\2\0\5\10\1\156"+
    "\16\10\27\0\3\10\2\0\5\10\1\157\16\10\27\0"+
    "\3\10\2\0\11\10\1\160\12\10\27\0\3\10\2\0"+
    "\22\10\1\161\1\10\27\0\3\10\2\0\23\10\1\162"+
    "\27\0\3\10\2\0\6\10\1\163\15\10\27\0\3\10"+
    "\2\0\11\10\1\164\12\10\27\0\3\10\2\0\15\10"+
    "\1\165\6\10\27\0\3\10\2\0\14\10\1\166\7\10"+
    "\22\0\1\106\1\167\1\137\1\47\1\107\53\106\1\140"+
    "\1\170\1\141\1\0\54\140\5\0\3\10\2\0\10\10"+
    "\1\171\13\10\27\0\3\10\2\0\15\10\1\172\6\10"+
    "\27\0\3\10\2\0\2\10\1\173\21\10\27\0\3\10"+
    "\2\0\1\10\1\174\22\10\27\0\3\10\2\0\6\10"+
    "\1\175\15\10\27\0\3\10\2\0\14\10\1\176\7\10"+
    "\27\0\3\10\2\0\20\10\1\177\3\10\27\0\3\10"+
    "\2\0\7\10\1\200\14\10\27\0\3\10\2\0\15\10"+
    "\1\201\6\10\27\0\3\10\2\0\11\10\1\202\12\10"+
    "\27\0\3\10\2\0\13\10\1\203\10\10\27\0\3\10"+
    "\2\0\10\10\1\204\13\10\27\0\3\10\2\0\13\10"+
    "\1\205\10\10\27\0\3\10\2\0\6\10\1\206\15\10"+
    "\27\0\3\10\2\0\16\10\1\207\5\10\27\0\3\10"+
    "\2\0\5\10\1\210\16\10\27\0\3\10\2\0\1\10"+
    "\1\211\22\10\27\0\3\10\2\0\5\10\1\212\16\10"+
    "\27\0\3\10\2\0\6\10\1\213\15\10\27\0\3\10"+
    "\2\0\5\10\1\214\16\10\27\0\3\10\2\0\2\10"+
    "\1\215\21\10\27\0\3\10\2\0\13\10\1\216\10\10"+
    "\27\0\3\10\2\0\17\10\1\217\4\10\27\0\3\10"+
    "\2\0\1\10\1\220\22\10\27\0\3\10\2\0\5\10"+
    "\1\221\16\10\27\0\3\10\2\0\15\10\1\222\6\10"+
    "\27\0\3\10\2\0\3\10\1\223\20\10\27\0\3\10"+
    "\2\0\5\10\1\224\16\10\27\0\3\10\2\0\10\10"+
    "\1\225\13\10\27\0\3\10\2\0\11\10\1\226\12\10"+
    "\27\0\3\10\2\0\5\10\1\227\16\10\27\0\3\10"+
    "\2\0\11\10\1\230\12\10\27\0\3\10\2\0\11\10"+
    "\1\231\12\10\27\0\3\10\2\0\13\10\1\232\10\10"+
    "\27\0\3\10\2\0\11\10\1\233\12\10\27\0\3\10"+
    "\2\0\10\10\1\234\13\10\27\0\3\10\2\0\1\10"+
    "\1\235\22\10\27\0\3\10\2\0\14\10\1\236\7\10"+
    "\27\0\3\10\2\0\5\10\1\237\16\10\27\0\3\10"+
    "\2\0\15\10\1\240\6\10\27\0\3\10\2\0\2\10"+
    "\1\241\21\10\27\0\3\10\2\0\1\10\1\242\22\10"+
    "\27\0\3\10\2\0\14\10\1\243\7\10\27\0\3\10"+
    "\2\0\13\10\1\244\10\10\27\0\3\10\2\0\14\10"+
    "\1\245\7\10\27\0\3\10\2\0\14\10\1\246\7\10"+
    "\27\0\3\10\2\0\10\10\1\247\13\10\27\0\3\10"+
    "\2\0\6\10\1\250\15\10\27\0\3\10\2\0\13\10"+
    "\1\251\10\10\27\0\3\10\2\0\4\10\1\252\17\10"+
    "\27\0\3\10\2\0\14\10\1\253\7\10\27\0\3\10"+
    "\2\0\5\10\1\254\16\10\27\0\3\10\2\0\11\10"+
    "\1\255\12\10\27\0\3\10\2\0\1\256\23\10\27\0"+
    "\3\10\2\0\13\10\1\257\10\10\27\0\3\10\2\0"+
    "\1\260\23\10\27\0\3\10\2\0\11\10\1\261\12\10"+
    "\27\0\3\10\2\0\1\262\23\10\27\0\3\10\2\0"+
    "\10\10\1\263\13\10\27\0\3\10\2\0\10\10\1\264"+
    "\13\10\27\0\3\10\2\0\11\10\1\265\12\10\27\0"+
    "\3\10\2\0\11\10\1\266\12\10\27\0\3\10\2\0"+
    "\11\10\1\267\12\10\27\0\3\10\2\0\6\10\1\270"+
    "\15\10\27\0\3\10\2\0\14\10\1\271\7\10\27\0"+
    "\3\10\2\0\13\10\1\272\10\10\27\0\3\10\2\0"+
    "\11\10\1\273\12\10\22\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[6720];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\2\11\3\1\1\11\22\1\2\11"+
    "\2\1\7\11\2\0\1\11\2\0\22\1\10\11\1\0"+
    "\2\1\1\11\25\1\3\0\132\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[187];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */

ListaErrores errores = ListaErrores.getListaerror();


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public AnalisisLex_CJS(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public AnalisisLex_CJS(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 176) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 52: 
          { System.out.println("Se reconocio reservada "+yytext());	
					return new Symbol(sym.retornar,yychar,yyline,yytext());
          }
        case 59: break;
        case 27: 
          { System.out.println("Se reconocio signo "+yytext());	
					return new Symbol(sym.and,yychar,yyline,yytext());
          }
        case 60: break;
        case 37: 
          { System.out.println("Se reconocio reservada "+yytext());	
					return new Symbol(sym.rdimv,yychar,yyline,yytext());
          }
        case 61: break;
        case 42: 
          { System.out.println("Se reconocio reservada "+yytext());	
					return new Symbol(sym.rlisto,yychar,yyline,yytext());
          }
        case 62: break;
        case 19: 
          { System.out.println("Se reconocio signo "+yytext());	
					return new Symbol(sym.coma,yychar,yyline,yytext());
          }
        case 63: break;
        case 31: 
          { System.out.println("Se reconocio signo "+yytext());	
					return new Symbol(sym.mayorigual,yychar,yyline,yytext());
          }
        case 64: break;
        case 49: 
          { System.out.println("Se reconocio reservada "+yytext());	
					return new Symbol(sym.funcion,yychar,yyline,yytext());
          }
        case 65: break;
        case 33: 
          { System.out.println("Se reconocio signo "+yytext());	
					return new Symbol(sym.incrementar,yychar,yyline,yytext());
          }
        case 66: break;
        case 2: 
          { System.out.println("Se reconocio signo "+yytext());	
					return new Symbol(sym.comillasimple,yychar,yyline,yytext());
          }
        case 67: break;
        case 44: 
          { System.out.println("Se reconocio reservada "+yytext());	
					return new Symbol(sym.rconteo,yychar,yyline,yytext());
          }
        case 68: break;
        case 17: 
          { System.out.println("Se reconocio signo "+yytext());	
					return new Symbol(sym.menos,yychar,yyline,yytext());
          }
        case 69: break;
        case 53: 
          { System.out.println("Se reconocio reservada "+yytext());	
					return new Symbol(sym.documento,yychar,yyline,yytext());
          }
        case 70: break;
        case 20: 
          { System.out.println("Se reconocio signo "+yytext());	
					return new Symbol(sym.dpuntos,yychar,yyline,yytext());
          }
        case 71: break;
        case 23: 
          { System.out.println("Se reconocio signo "+yytext());	
					return new Symbol(sym.allave,yychar,yyline,yytext());
          }
        case 72: break;
        case 12: 
          { System.out.println("Se reconocio signo "+yytext());	
					return new Symbol(sym.mayor,yychar,yyline,yytext());
          }
        case 73: break;
        case 26: 
          { System.out.println("Se reconocio reservada "+yytext());	
					return new Symbol(sym.si,yychar,yyline,yytext());
          }
        case 74: break;
        case 9: 
          { System.out.println("Se reconocio signo "+yytext());	
					return new Symbol(sym.comillas,yychar,yyline,yytext());
          }
        case 75: break;
        case 54: 
          { System.out.println("Se reconocio reservada "+yytext());	
					return new Symbol(sym.rcliqueado,yychar,yyline,yytext());
          }
        case 76: break;
        case 7: 
          { /*String cadaux = yytext().toLowerCase().replace("\"","");
					if(cadaux.equals("false")){
						System.out.println("Se reconocio boolean "+yytext());	
						return new Symbol(sym.rtrue,yychar,yyline,yytext());
					}else if(cadaux.equals("true")){
						System.out.println("Se reconocio boolean "+yytext());	
						return new Symbol(sym.rtrue,yychar,yyline,yytext());
					}*///else{
						System.out.println("Se reconocio identificador "+yytext());	
						return new Symbol(sym.iden,yychar,yyline, new String(yytext()));	
					//}
          }
        case 77: break;
        case 56: 
          { System.out.println("Se reconocio reservada "+yytext());	
					return new Symbol(sym.selecciona,yychar,yyline,yytext());
          }
        case 78: break;
        case 48: 
          { System.out.println("Se reconocio reservada "+yytext());	
					return new Symbol(sym.obtener,yychar,yyline,yytext());
          }
        case 79: break;
        case 55: 
          { System.out.println("Se reconocio reservada "+yytext());	
					return new Symbol(sym.rmodificado,yychar,yyline,yytext());
          }
        case 80: break;
        case 46: 
          { System.out.println("Se reconocio reservada "+yytext());	
					return new Symbol(sym.defecto,yychar,yyline,yytext());
          }
        case 81: break;
        case 50: 
          { System.out.println("Se reconocio etiqueta "+yytext());	
					return new Symbol(sym.imprimir,yychar,yyline,yytext());
          }
        case 82: break;
        case 41: 
          { /* Se ignoran */
					/*if(yytext().toLowerCase().equals("'false'")){
						return new Symbol(sym.rfalse,yychar,yyline,yytext());
					}else if(yytext().toLowerCase().equals("'true'")){
						return new Symbol(sym.rtrue,yychar,yyline,yytext());
					}*/
          }
        case 83: break;
        case 15: 
          { System.out.println("Se reconocio signo "+yytext());	
					return new Symbol(sym.pot,yychar,yyline,yytext());
          }
        case 84: break;
        case 10: 
          { System.out.println("Se reconocio signo "+yytext());	
					return new Symbol(sym.igual,yychar,yyline,yytext());
          }
        case 85: break;
        case 28: 
          { System.out.println("Se reconocio signo "+yytext());	
					return new Symbol(sym.or,yychar,yyline,yytext());
          }
        case 86: break;
        case 43: 
          { System.out.println("Se reconocio reservada "+yytext());	
					return new Symbol(sym.atexto,yychar,yyline,yytext());
          }
        case 87: break;
        case 24: 
          { System.out.println("Se reconocio signo "+yytext());	
					return new Symbol(sym.cllave,yychar,yyline,yytext());
          }
        case 88: break;
        case 39: 
          { System.out.println("Se reconocio reservada "+yytext());	
					return new Symbol(sym.caso,yychar,yyline,yytext());
          }
        case 89: break;
        case 32: 
          { System.out.println("Se reconocio signo "+yytext());	
					return new Symbol(sym.diferente,yychar,yyline,yytext());
          }
        case 90: break;
        case 11: 
          { System.out.println("Se reconocio signo "+yytext());	
					return new Symbol(sym.menor,yychar,yyline,yytext());
          }
        case 91: break;
        case 18: 
          { System.out.println("Se reconocio signo "+yytext());	
					return new Symbol(sym.pcoma,yychar,yyline,yytext());
          }
        case 92: break;
        case 58: 
          { System.out.println("Se reconocio reservada "+yytext());	
					return new Symbol(sym.setelemento,yychar,yyline,yytext());
          }
        case 93: break;
        case 36: 
          { String cadaux = yytext().toLowerCase().replace("\"","");
					if(cadaux.equals("false")){
						System.out.println("Se reconocio boolean "+yytext());	
						return new Symbol(sym.rfalse,yychar,yyline,yytext());
					}else if(cadaux.equals("true")){
						System.out.println("Se reconocio boolean "+yytext());	
						return new Symbol(sym.rtrue,yychar,yyline,yytext());
					}else{
						String valor = cadaux.toString();
						String[] vec = valor.split("/");
			            if (vec.length == 3) {
			                String date = vec[vec.length - 1];
			                valor = date;
			                vec = valor.split(":");
			                if (vec.length == 3) {
			                    date = vec[vec.length - 1];
			                    if (date.length() > 2) {
			                        System.out.println("Se reconocio cadena "+yytext());	
									return new Symbol(sym.cadena,yychar,yyline, new String(yytext()));
			                    }
			                        System.out.println("Se reconocio datetime"+yytext());	
									return new Symbol(sym.dateti,yychar,yyline, new String(yytext()));
			                } else {
			                    System.out.println("Se reconocio date"+yytext());	
									return new Symbol(sym.date,yychar,yyline, new String(yytext()));
			                }
			            }
						System.out.println("Se reconocio cadena "+yytext());	
						return new Symbol(sym.cadena,yychar,yyline, new String(yytext()));
					}
          }
        case 94: break;
        case 35: 
          { System.out.println("Se reconocio decimal "+yytext());	
					return new Symbol(sym.decimal,yychar,yyline, yytext());
          }
        case 95: break;
        case 5: 
          { /* Se ignoran */ yychar = 0;
          }
        case 96: break;
        case 21: 
          { System.out.println("Se reconocio signo "+yytext());	
					return new Symbol(sym.aparen,yychar,yyline,yytext());
          }
        case 97: break;
        case 29: 
          { System.out.println("Se reconocio signo "+yytext());	
					return new Symbol(sym.igualacion,yychar,yyline,yytext());
          }
        case 98: break;
        case 1: 
          { System.out.println("Error lexico: "+yytext());
				errores.agregarerror(new ER(yyline,yycolumn, yytext(), 1, ""
                                + "Caracter no conocido"));
          }
        case 99: break;
        case 38: 
          { System.out.println("Se reconocio reservada "+yytext());	
					return new Symbol(sym.sino,yychar,yyline,yytext());
          }
        case 100: break;
        case 6: 
          { System.out.println("Se reconocio numero "+yytext());	
					return new Symbol(sym.num,yychar,yyline,yytext());
          }
        case 101: break;
        case 13: 
          { System.out.println("Se reconocio signo "+yytext());	
					return new Symbol(sym.not,yychar,yyline,yytext());
          }
        case 102: break;
        case 8: 
          { System.out.println("Se reconocio signo "+yytext());	
					return new Symbol(sym.punto,yychar,yyline,yytext());
          }
        case 103: break;
        case 51: 
          { System.out.println("Se reconocio reservada "+yytext());	
					return new Symbol(sym.mientras,yychar,yyline,yytext());
          }
        case 104: break;
        case 22: 
          { System.out.println("Se reconocio signo "+yytext());	
					return new Symbol(sym.cparen,yychar,yyline,yytext());
          }
        case 105: break;
        case 3: 
          { System.out.println("Se reconocio signo "+yytext());	
					return new Symbol(sym.div,yychar,yyline,yytext());
          }
        case 106: break;
        case 45: 
          { System.out.println("Se reconocio etiqueta "+yytext());	
					return new Symbol(sym.detener,yychar,yyline,yytext());
          }
        case 107: break;
        case 16: 
          { System.out.println("Se reconocio signo "+yytext());	
					return new Symbol(sym.mas,yychar,yyline,yytext());
          }
        case 108: break;
        case 25: 
          { /* Se ignoran */
          }
        case 109: break;
        case 47: 
          { System.out.println("Se reconocio reservada "+yytext());	
					return new Symbol(sym.mensaje,yychar,yyline,yytext());
          }
        case 110: break;
        case 34: 
          { System.out.println("Se reconocio signo "+yytext());	
					return new Symbol(sym.decrementar,yychar,yyline,yytext());
          }
        case 111: break;
        case 57: 
          { System.out.println("Se reconocio reservada "+yytext());	
					return new Symbol(sym.observador,yychar,yyline,yytext());
          }
        case 112: break;
        case 4: 
          { System.out.println("Se reconocio signo "+yytext());	
					return new Symbol(sym.por,yychar,yyline,yytext());
          }
        case 113: break;
        case 40: 
          { System.out.println("Se reconocio reservada "+yytext());	
					return new Symbol(sym.para,yychar,yyline,yytext());
          }
        case 114: break;
        case 14: 
          { System.out.println("Se reconocio signo "+yytext());	
					return new Symbol(sym.mod,yychar,yyline,yytext());
          }
        case 115: break;
        case 30: 
          { System.out.println("Se reconocio signo "+yytext());	
					return new Symbol(sym.menorigual,yychar,yyline,yytext());
          }
        case 116: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
