
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Mar 09 22:58:11 CST 2018
//----------------------------------------------------

package Gramaticas.CJS;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int dateti = 58;
  public static final int rlisto = 54;
  public static final int allave = 42;
  public static final int cllave = 43;
  public static final int mod = 28;
  public static final int imprimir = 10;
  public static final int detener = 11;
  public static final int coma = 53;
  public static final int igual = 36;
  public static final int rcliqueado = 56;
  public static final int dpuntos = 38;
  public static final int rmodificado = 55;
  public static final int si = 18;
  public static final int mientras = 12;
  public static final int comillasimple = 44;
  public static final int igualacion = 23;
  public static final int iden = 48;
  public static final int observador = 5;
  public static final int defecto = 14;
  public static final int menos = 33;
  public static final int menor = 34;
  public static final int decrementar = 52;
  public static final int EOF = 0;
  public static final int comillas = 57;
  public static final int mas = 32;
  public static final int para = 13;
  public static final int incrementar = 51;
  public static final int error = 1;
  public static final int pcoma = 37;
  public static final int mayor = 35;
  public static final int or = 22;
  public static final int pot = 29;
  public static final int menorigual = 24;
  public static final int rconteo = 20;
  public static final int por = 31;
  public static final int punto = 39;
  public static final int mensaje = 7;
  public static final int funcion = 9;
  public static final int rfalse = 46;
  public static final int obtener = 4;
  public static final int caso = 15;
  public static final int mayorigual = 25;
  public static final int setelemento = 3;
  public static final int documento = 6;
  public static final int diferente = 26;
  public static final int and = 21;
  public static final int not = 27;
  public static final int atexto = 19;
  public static final int retornar = 8;
  public static final int rdimv = 2;
  public static final int date = 59;
  public static final int aparen = 40;
  public static final int div = 30;
  public static final int num = 47;
  public static final int cparen = 41;
  public static final int selecciona = 16;
  public static final int decimal = 50;
  public static final int rtrue = 45;
  public static final int cadena = 49;
  public static final int sino = 17;
}

