/* The following code was generated by JFlex 1.4.3 on 9/03/18 10:59 PM */

package Gramaticas.CHTML;

import Errores.ListaErrores;
import java_cup.runtime.Symbol;
import Errores.ER;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 9/03/18 10:59 PM from the specification file
 * <tt>lexicoCHTML.jflex</tt>
 */
public class AnalisisLex_CHTML implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\47\1\12\1\0\2\47\22\0\1\47\1\0\1\11\5\0"+
    "\1\45\1\46\1\4\2\0\1\3\1\0\1\2\12\6\1\0\1\44"+
    "\1\1\1\43\1\5\2\0\1\24\1\25\1\13\1\27\1\23\1\20"+
    "\1\40\1\14\1\21\1\31\1\37\1\17\1\16\1\22\1\30\1\35"+
    "\1\42\1\33\1\32\1\15\1\34\1\41\1\7\1\36\1\7\1\26"+
    "\4\0\1\10\1\0\1\24\1\25\1\13\1\27\1\23\1\20\1\40"+
    "\1\14\1\21\1\31\1\37\1\17\1\16\1\22\1\30\1\35\1\42"+
    "\1\33\1\32\1\15\1\34\1\41\1\7\1\36\1\7\1\26\126\0"+
    "\1\7\37\0\1\7\uff0e\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\1\1"+
    "\1\7\16\6\1\10\1\11\1\12\1\13\2\0\2\6"+
    "\1\14\3\6\1\15\11\6\1\16\14\6\1\0\1\17"+
    "\5\6\1\20\5\6\1\21\21\6\1\0\1\22\3\6"+
    "\1\23\12\6\1\24\7\6\1\25\3\6\1\0\1\26"+
    "\1\27\4\6\1\30\1\31\1\32\1\33\5\6\1\34"+
    "\1\35\2\6\1\36\1\6\1\37\1\40\1\41\1\0"+
    "\2\6\1\42\1\43\1\6\1\44\2\6\1\45\2\6"+
    "\1\46\1\6\1\0\2\6\1\47\3\6\1\50\1\51"+
    "\1\0\1\52\3\6\1\53\1\54\1\6\1\55\1\6"+
    "\1\56\1\57";

  private static int [] zzUnpackAction() {
    int [] result = new int[177];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\50\0\120\0\50\0\50\0\170\0\240\0\310"+
    "\0\360\0\u0118\0\u0140\0\u0168\0\u0190\0\u01b8\0\u01e0\0\u0208"+
    "\0\u0230\0\u0258\0\u0280\0\u02a8\0\u02d0\0\u02f8\0\u0320\0\50"+
    "\0\50\0\50\0\50\0\u0348\0\u0370\0\u0398\0\u03c0\0\240"+
    "\0\u03e8\0\u0410\0\u0438\0\240\0\u0460\0\u0488\0\u04b0\0\u04d8"+
    "\0\u0500\0\u0528\0\u0550\0\u0578\0\u05a0\0\240\0\u05c8\0\u05f0"+
    "\0\u0618\0\u0640\0\u0668\0\u0690\0\u06b8\0\u06e0\0\u0708\0\u0730"+
    "\0\u0758\0\u0780\0\u07a8\0\50\0\u07d0\0\u07f8\0\u0820\0\u0848"+
    "\0\u0870\0\240\0\u0898\0\u08c0\0\u08e8\0\u0910\0\u0938\0\240"+
    "\0\u0960\0\u0988\0\u09b0\0\u09d8\0\u0a00\0\u0a28\0\u0a50\0\u0a78"+
    "\0\u0aa0\0\u0ac8\0\u0af0\0\u0b18\0\u0b40\0\u0b68\0\u0b90\0\u0bb8"+
    "\0\u0be0\0\u0c08\0\240\0\u0c30\0\u0c58\0\u0c80\0\u0ca8\0\u0cd0"+
    "\0\u0cf8\0\u0d20\0\u0d48\0\u0d70\0\u0d98\0\u0dc0\0\u0de8\0\u0e10"+
    "\0\u0e38\0\240\0\u0e60\0\u0e88\0\u0eb0\0\u0ed8\0\u0f00\0\u0f28"+
    "\0\u0f50\0\240\0\u0f78\0\u0fa0\0\u0fc8\0\u0ff0\0\240\0\240"+
    "\0\u1018\0\u1040\0\u1068\0\u1090\0\u10b8\0\240\0\240\0\240"+
    "\0\u10e0\0\u1108\0\u1130\0\u1158\0\u1180\0\240\0\240\0\u11a8"+
    "\0\u11d0\0\240\0\u11f8\0\240\0\240\0\240\0\u1220\0\u1248"+
    "\0\u1270\0\240\0\240\0\u1298\0\240\0\u12c0\0\u12e8\0\240"+
    "\0\u1310\0\u1338\0\240\0\u1360\0\u1388\0\u13b0\0\u13d8\0\240"+
    "\0\u1400\0\u1428\0\u1450\0\240\0\240\0\u1478\0\240\0\u14a0"+
    "\0\u14c8\0\u14f0\0\240\0\u0ff0\0\u1518\0\240\0\u1540\0\240"+
    "\0\240";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[177];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\2\1\4\1\2\1\5\1\6\1\7"+
    "\1\2\1\10\1\11\1\12\1\7\1\13\2\7\1\14"+
    "\1\15\1\7\1\16\1\17\1\20\1\7\1\21\1\22"+
    "\1\7\1\23\1\24\1\7\1\25\2\7\1\26\1\27"+
    "\1\7\1\30\1\31\1\32\1\33\1\11\52\0\1\34"+
    "\53\0\1\6\47\0\3\7\2\0\30\7\5\0\12\35"+
    "\1\0\35\35\12\0\1\11\34\0\1\11\6\0\3\7"+
    "\2\0\1\36\1\37\1\40\1\7\1\41\3\7\1\42"+
    "\1\43\1\44\3\7\1\45\2\7\1\46\6\7\13\0"+
    "\3\7\2\0\6\7\1\47\1\7\1\50\1\51\16\7"+
    "\13\0\3\7\2\0\6\7\1\52\6\7\1\53\12\7"+
    "\13\0\3\7\2\0\3\7\1\54\7\7\1\55\1\56"+
    "\13\7\13\0\3\7\2\0\7\7\1\57\20\7\13\0"+
    "\3\7\2\0\4\7\1\60\2\7\1\61\20\7\13\0"+
    "\3\7\2\0\15\7\1\62\12\7\13\0\3\7\2\0"+
    "\10\7\1\63\17\7\13\0\3\7\2\0\22\7\1\64"+
    "\5\7\13\0\3\7\2\0\11\7\1\65\10\7\1\66"+
    "\5\7\13\0\3\7\2\0\21\7\1\67\6\7\13\0"+
    "\3\7\2\0\11\7\1\70\16\7\13\0\3\7\2\0"+
    "\20\7\1\71\7\7\13\0\3\7\2\0\11\7\1\72"+
    "\16\7\7\0\1\73\45\0\11\35\1\74\36\35\6\0"+
    "\3\7\2\0\17\7\1\75\10\7\13\0\3\7\2\0"+
    "\2\7\1\76\25\7\13\0\3\7\2\0\6\7\1\77"+
    "\21\7\13\0\3\7\2\0\7\7\1\100\20\7\13\0"+
    "\3\7\2\0\16\7\1\101\11\7\13\0\3\7\2\0"+
    "\17\7\1\102\10\7\13\0\3\7\2\0\10\7\1\103"+
    "\17\7\13\0\3\7\2\0\2\7\1\104\25\7\13\0"+
    "\3\7\2\0\23\7\1\105\4\7\13\0\3\7\2\0"+
    "\12\7\1\106\15\7\13\0\3\7\2\0\4\7\1\107"+
    "\2\7\1\110\20\7\13\0\3\7\2\0\7\7\1\111"+
    "\20\7\13\0\3\7\2\0\11\7\1\112\16\7\13\0"+
    "\3\7\2\0\27\7\1\113\13\0\3\7\2\0\1\114"+
    "\3\7\1\115\23\7\13\0\3\7\2\0\2\7\1\116"+
    "\3\7\1\117\21\7\13\0\3\7\2\0\1\120\27\7"+
    "\13\0\3\7\2\0\2\7\1\121\25\7\13\0\3\7"+
    "\2\0\20\7\1\122\7\7\13\0\3\7\2\0\1\123"+
    "\27\7\13\0\3\7\2\0\4\7\1\124\23\7\13\0"+
    "\3\7\2\0\6\7\1\125\21\7\13\0\3\7\2\0"+
    "\2\7\1\126\25\7\13\0\3\7\2\0\7\7\1\127"+
    "\20\7\13\0\3\7\2\0\21\7\1\130\6\7\13\0"+
    "\3\7\2\0\4\7\1\131\23\7\10\0\1\132\52\0"+
    "\3\7\2\0\17\7\1\133\10\7\13\0\3\7\2\0"+
    "\3\7\1\134\24\7\13\0\3\7\2\0\1\135\27\7"+
    "\13\0\3\7\2\0\2\7\1\136\25\7\13\0\3\7"+
    "\2\0\11\7\1\137\16\7\13\0\3\7\2\0\20\7"+
    "\1\140\7\7\13\0\3\7\2\0\21\7\1\141\6\7"+
    "\13\0\3\7\2\0\2\7\1\142\25\7\13\0\3\7"+
    "\2\0\4\7\1\143\23\7\13\0\2\7\1\144\2\0"+
    "\30\7\13\0\3\7\2\0\14\7\1\145\13\7\13\0"+
    "\3\7\2\0\25\7\1\146\2\7\13\0\3\7\2\0"+
    "\21\7\1\147\6\7\13\0\3\7\2\0\11\7\1\150"+
    "\16\7\13\0\3\7\2\0\11\7\1\151\16\7\13\0"+
    "\3\7\2\0\15\7\1\152\12\7\13\0\3\7\2\0"+
    "\7\7\1\153\20\7\13\0\3\7\2\0\1\7\1\154"+
    "\26\7\13\0\3\7\2\0\15\7\1\155\12\7\13\0"+
    "\3\7\2\0\10\7\1\156\17\7\13\0\3\7\2\0"+
    "\6\7\1\157\21\7\13\0\3\7\2\0\2\7\1\160"+
    "\25\7\13\0\3\7\2\0\7\7\1\161\20\7\13\0"+
    "\3\7\2\0\11\7\1\162\16\7\13\0\3\7\2\0"+
    "\10\7\1\163\17\7\13\0\3\7\2\0\22\7\1\164"+
    "\5\7\13\0\3\7\2\0\15\7\1\165\12\7\5\0"+
    "\4\166\1\0\43\166\6\0\3\7\2\0\4\7\1\167"+
    "\23\7\13\0\3\7\2\0\24\7\1\170\3\7\13\0"+
    "\3\7\2\0\20\7\1\171\7\7\13\0\2\7\1\172"+
    "\2\0\30\7\13\0\3\7\2\0\22\7\1\173\5\7"+
    "\13\0\3\7\2\0\4\7\1\174\23\7\13\0\3\7"+
    "\2\0\15\7\1\175\12\7\13\0\3\7\2\0\11\7"+
    "\1\176\16\7\13\0\3\7\2\0\2\7\1\177\25\7"+
    "\13\0\3\7\2\0\15\7\1\200\12\7\13\0\3\7"+
    "\2\0\10\7\1\201\17\7\13\0\3\7\2\0\6\7"+
    "\1\202\21\7\13\0\3\7\2\0\12\7\1\203\15\7"+
    "\13\0\3\7\2\0\1\204\27\7\13\0\3\7\2\0"+
    "\10\7\1\205\17\7\13\0\3\7\2\0\15\7\1\206"+
    "\12\7\13\0\3\7\2\0\7\7\1\207\20\7\13\0"+
    "\3\7\2\0\1\210\27\7\13\0\3\7\2\0\15\7"+
    "\1\211\12\7\13\0\3\7\2\0\15\7\1\212\12\7"+
    "\13\0\3\7\2\0\7\7\1\213\20\7\13\0\3\7"+
    "\2\0\4\7\1\214\23\7\13\0\3\7\2\0\15\7"+
    "\1\215\12\7\13\0\3\7\2\0\20\7\1\216\7\7"+
    "\5\0\3\166\1\217\1\0\43\166\6\0\3\7\2\0"+
    "\11\7\1\220\16\7\13\0\3\7\2\0\2\7\1\221"+
    "\25\7\13\0\3\7\2\0\15\7\1\222\12\7\13\0"+
    "\3\7\2\0\15\7\1\223\12\7\13\0\2\7\1\224"+
    "\2\0\30\7\13\0\3\7\2\0\7\7\1\225\20\7"+
    "\13\0\3\7\2\0\10\7\1\226\17\7\13\0\3\7"+
    "\2\0\10\7\1\227\17\7\13\0\3\7\2\0\10\7"+
    "\1\230\17\7\13\0\3\7\2\0\11\7\1\231\16\7"+
    "\13\0\3\7\2\0\1\7\1\232\26\7\13\0\3\7"+
    "\2\0\7\7\1\233\20\7\13\0\3\7\2\0\10\7"+
    "\1\234\17\7\5\0\2\166\1\235\1\217\1\0\43\166"+
    "\6\0\3\7\2\0\14\7\1\236\13\7\13\0\3\7"+
    "\2\0\10\7\1\237\17\7\13\0\3\7\2\0\11\7"+
    "\1\240\16\7\13\0\3\7\2\0\20\7\1\241\7\7"+
    "\13\0\3\7\2\0\13\7\1\242\14\7\13\0\3\7"+
    "\2\0\14\7\1\243\13\7\13\0\3\7\2\0\11\7"+
    "\1\244\16\7\13\0\3\7\2\0\20\7\1\245\7\7"+
    "\5\0\2\166\1\246\1\217\1\0\43\166\6\0\3\7"+
    "\2\0\15\7\1\247\12\7\13\0\3\7\2\0\23\7"+
    "\1\250\4\7\13\0\3\7\2\0\14\7\1\251\13\7"+
    "\13\0\3\7\2\0\11\7\1\252\16\7\13\0\3\7"+
    "\2\0\15\7\1\253\12\7\5\0\3\166\1\217\1\0"+
    "\1\254\42\166\6\0\3\7\2\0\2\7\1\255\25\7"+
    "\13\0\3\7\2\0\11\7\1\256\16\7\13\0\3\7"+
    "\2\0\14\7\1\257\13\7\13\0\3\7\2\0\15\7"+
    "\1\260\12\7\13\0\3\7\2\0\15\7\1\261\12\7"+
    "\5\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5480];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\2\11\22\1\4\11\2\0\35\1"+
    "\1\0\1\11\35\1\1\0\33\1\1\0\30\1\1\0"+
    "\15\1\1\0\10\1\1\0\13\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[177];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */

ListaErrores errores = ListaErrores.getListaerror();


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public AnalisisLex_CHTML(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public AnalisisLex_CHTML(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 168) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 47: 
          { System.out.println("Se reconocio etiqueta "+yytext());	
					return new Symbol(sym.eencabezado,yychar,yyline,yytext());
          }
        case 48: break;
        case 6: 
          { System.out.println("Se reconocio identificador "+yytext());	
					return new Symbol(sym.iden,yychar,yyline, new String(yytext()));
          }
        case 49: break;
        case 21: 
          { System.out.println("Se reconocio propiedad "+yytext());	
					return new Symbol(sym.pruta,yychar,yyline,yytext());
          }
        case 50: break;
        case 26: 
          { System.out.println("Se reconocio etiqueta "+yytext());	
					return new Symbol(sym.efila,yychar,yyline,yytext());
          }
        case 51: break;
        case 31: 
          { System.out.println("Se reconocio etiqueta "+yytext());	
					return new Symbol(sym.epanel,yychar,yyline,yytext());
          }
        case 52: break;
        case 39: 
          { System.out.println("Se reconocio etiqueta "+yytext());	
					return new Symbol(sym.eareatexto,yychar,yyline,yytext());
          }
        case 53: break;
        case 32: 
          { System.out.println("Se reconocio propiedad "+yytext());	
					return new Symbol(sym.pgrupo,yychar,yyline,yytext());
          }
        case 54: break;
        case 36: 
          { System.out.println("Se reconocio etiqueta "+yytext());	
					return new Symbol(sym.eimagen,yychar,yyline,yytext());
          }
        case 55: break;
        case 1: 
          { System.out.println("Error lexico: "+yytext());
errores.agregarerror(new ER(yyline,yycolumn, yytext(), 1, ""
                                + "Caracter no conocido"));
          }
        case 56: break;
        case 3: 
          { System.out.println("Se reconocio signo "+yytext());	
					return new Symbol(sym.menos,yychar,yyline,yytext());
          }
        case 57: break;
        case 13: 
          { System.out.println("Se reconocio etiqueta "+yytext());	
					return new Symbol(sym.eceldaencabezado,yychar,yyline,yytext());
          }
        case 58: break;
        case 4: 
          { System.out.println("Se reconocio signo "+yytext());	
					return new Symbol(sym.mayor,yychar,yyline,yytext());
          }
        case 59: break;
        case 30: 
          { System.out.println("Se reconocio etiqueta "+yytext());	
					return new Symbol(sym.esalto,yychar,yyline,yytext());
          }
        case 60: break;
        case 16: 
          { System.out.println("Se reconocio etiqueta "+yytext());	
					return new Symbol(sym.ecjs,yychar,yyline,yytext());
          }
        case 61: break;
        case 38: 
          { System.out.println("Se reconocio etiqueta "+yytext());	
					return new Symbol(sym.eopcion,yychar,yyline,yytext());
          }
        case 62: break;
        case 37: 
          { System.out.println("Se reconocio etiqueta "+yytext());	
					return new Symbol(sym.eenlace,yychar,yyline,yytext());
          }
        case 63: break;
        case 23: 
          { System.out.println("Se reconocio propiedad "+yytext());	
					return new Symbol(sym.eclick,yychar,yyline,yytext());
          }
        case 64: break;
        case 25: 
          { System.out.println("Se reconocio etiqueta "+yytext());	
					return new Symbol(sym.etabla,yychar,yyline,yytext());
          }
        case 65: break;
        case 19: 
          { System.out.println("Se reconocio etiqueta "+yytext());	
					return new Symbol(sym.ecajaopciones,yychar,yyline,yytext());
          }
        case 66: break;
        case 15: 
          { System.out.println("Se reconocio cadena "+yytext());	
					return new Symbol(sym.cadena,yychar,yyline, yytext());
          }
        case 67: break;
        case 8: 
          { System.out.println("Se reconocio signo "+yytext());	
					return new Symbol(sym.igual,yychar,yyline,yytext());
          }
        case 68: break;
        case 17: 
          { System.out.println("Se reconocio etiqueta "+yytext());	
					return new Symbol(sym.efin,yychar,yyline,yytext());
          }
        case 69: break;
        case 18: 
          { System.out.println("Se reconocio etiqueta "+yytext());	
					return new Symbol(sym.eccss,yychar,yyline,yytext());
          }
        case 70: break;
        case 2: 
          { System.out.println("Se reconocio signo "+yytext());	
					return new Symbol(sym.menor,yychar,yyline,yytext());
          }
        case 71: break;
        case 9: 
          { System.out.println("Se reconocio signo "+yytext());	
					return new Symbol(sym.pcoma,yychar,yyline,yytext());
          }
        case 72: break;
        case 24: 
          { System.out.println("Se reconocio etiqueta "+yytext());	
					return new Symbol(sym.etexto,yychar,yyline,yytext());
          }
        case 73: break;
        case 29: 
          { System.out.println("Se reconocio etiqueta "+yytext());	
					return new Symbol(sym.eboton,yychar,yyline,yytext());
          }
        case 74: break;
        case 41: 
          { System.out.println("Se reconocio etiqueta "+yytext());	
					return new Symbol(sym.econtador,yychar,yyline,yytext());
          }
        case 75: break;
        case 7: 
          { /* Se ignoran */ yychar = 0;
          }
        case 76: break;
        case 27: 
          { System.out.println("Se reconocio propiedad "+yytext());	
					return new Symbol(sym.efondo,yychar,yyline,yytext());
          }
        case 77: break;
        case 10: 
          { System.out.println("Se reconocio signo "+yytext());	
					return new Symbol(sym.aparen,yychar,yyline,yytext());
          }
        case 78: break;
        case 42: 
          { System.out.println("Se reconocio propiedad "+yytext());	
					return new Symbol(sym.pcentrado,yychar,yyline,yytext());
          }
        case 79: break;
        case 14: 
          { System.out.println("Se reconocio propiedad "+yytext());	
					return new Symbol(sym.pid,yychar,yyline,yytext());
          }
        case 80: break;
        case 34: 
          { System.out.println("Se reconocio etiqueta "+yytext());	
					return new Symbol(sym.ecuerpo,yychar,yyline,yytext());
          }
        case 81: break;
        case 12: 
          { System.out.println("Se reconocio etiqueta "+yytext());	
					return new Symbol(sym.ecelda,yychar,yyline,yytext());
          }
        case 82: break;
        case 46: 
          { System.out.println("Se reconocio etiqueta "+yytext());	
					return new Symbol(sym.ecajatexto,yychar,yyline,yytext());
          }
        case 83: break;
        case 5: 
          { System.out.println("Se reconocio numero "+yytext());	
					return new Symbol(sym.num,yychar,yyline,yytext());
          }
        case 84: break;
        case 11: 
          { System.out.println("Se reconocio signo "+yytext());	
					return new Symbol(sym.cparen,yychar,yyline,yytext());
          }
        case 85: break;
        case 20: 
          { System.out.println("Se reconocio propiedad "+yytext());	
					return new Symbol(sym.palto,yychar,yyline,yytext());
          }
        case 86: break;
        case 43: 
          { System.out.println("Se reconocio propiedad "+yytext());	
					return new Symbol(sym.palineado,yychar,yyline,yytext());
          }
        case 87: break;
        case 44: 
          { /* Se ignoran */
          }
        case 88: break;
        case 35: 
          { System.out.println("Se reconocio etiqueta "+yytext());	
					return new Symbol(sym.etitulo,yychar,yyline,yytext());
          }
        case 89: break;
        case 22: 
          { System.out.println("Se reconocio etiqueta "+yytext());	
					return new Symbol(sym.echtml,yychar,yyline,yytext());
          }
        case 90: break;
        case 45: 
          { System.out.println("Se reconocio propiedad "+yytext());	
					return new Symbol(sym.pizquierda,yychar,yyline,yytext());
          }
        case 91: break;
        case 33: 
          { System.out.println("Se reconocio propiedad "+yytext());	
					return new Symbol(sym.evalor,yychar,yyline,yytext());
          }
        case 92: break;
        case 28: 
          { System.out.println("Se reconocio propiedad "+yytext());	
					return new Symbol(sym.pancho,yychar,yyline,yytext());
          }
        case 93: break;
        case 40: 
          { System.out.println("Se reconocio propiedad "+yytext());	
					return new Symbol(sym.pderecha,yychar,yyline,yytext());
          }
        case 94: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
