
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Mar 09 22:59:28 CST 2018
//----------------------------------------------------

package Gramaticas.CHTML;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int eenlace = 17;
  public static final int eceldaencabezado = 20;
  public static final int etitulo = 11;
  public static final int eboton = 16;
  public static final int pizquierda = 43;
  public static final int palineado = 32;
  public static final int pgrupo = 29;
  public static final int rparrafo = 46;
  public static final int ecjs = 5;
  public static final int igual = 34;
  public static final int efin = 3;
  public static final int efondo = 9;
  public static final int eareatexto = 22;
  public static final int ecelda = 21;
  public static final int eimagen = 15;
  public static final int iden = 41;
  public static final int epanel = 10;
  public static final int menos = 33;
  public static final int menor = 38;
  public static final int EOF = 0;
  public static final int pcentrado = 45;
  public static final int error = 1;
  public static final int pcoma = 35;
  public static final int mayor = 39;
  public static final int echtml = 2;
  public static final int etabla = 18;
  public static final int palto = 30;
  public static final int pid = 28;
  public static final int evalor = 25;
  public static final int pruta = 6;
  public static final int eclick = 14;
  public static final int eccss = 7;
  public static final int efila = 19;
  public static final int ecajaopciones = 23;
  public static final int pancho = 31;
  public static final int ecajatexto = 13;
  public static final int ecuerpo = 8;
  public static final int econtador = 26;
  public static final int aparen = 36;
  public static final int eencabezado = 4;
  public static final int etexto = 12;
  public static final int num = 40;
  public static final int cparen = 37;
  public static final int esalto = 27;
  public static final int pderecha = 44;
  public static final int cadena = 42;
  public static final int eopcion = 24;
}

