/* The following code was generated by JFlex 1.4.3 on 9/03/18 10:58 PM */

package Gramaticas.CSS;

import Errores.ListaErrores;
import java_cup.runtime.Symbol;
import Errores.ER;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 9/03/18 10:58 PM from the specification file
 * <tt>lexicoCCSS.jflex</tt>
 */
public class AnalisisLex_CCSS implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\53\1\3\1\0\2\53\22\0\1\53\1\0\1\10\5\0"+
    "\1\51\1\52\1\2\1\44\1\50\1\33\1\7\1\1\12\4\1\45"+
    "\1\47\1\0\1\46\3\0\1\23\1\35\1\24\1\12\1\14\1\34"+
    "\1\20\1\40\1\11\1\41\1\5\1\22\1\30\1\17\1\16\1\32"+
    "\1\36\1\21\1\26\1\13\1\25\1\27\1\5\1\15\1\31\1\37"+
    "\1\42\1\0\1\43\1\0\1\6\1\0\1\23\1\35\1\24\1\12"+
    "\1\14\1\34\1\20\1\40\1\11\1\41\1\5\1\22\1\30\1\17"+
    "\1\16\1\32\1\36\1\21\1\26\1\13\1\25\1\27\1\5\1\15"+
    "\1\31\1\37\126\0\1\5\37\0\1\5\uff0e\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\1\1"+
    "\13\6\1\7\4\6\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\4\0\1\21\30\6\1\22"+
    "\1\0\1\23\1\24\31\6\1\0\3\6\1\25\27\6"+
    "\1\26\3\6\1\27\1\30\14\6\1\31\1\32\4\6"+
    "\1\33\1\34\20\6\1\35\6\6\1\36\1\37\4\6"+
    "\1\40\3\6\1\41\1\42\1\6\1\43\1\6\1\0"+
    "\1\44\5\6\1\45\1\6\1\46\1\47\1\50\1\51"+
    "\5\6\1\52\3\6\1\53\3\6\1\54\1\6\1\55";

  private static int [] zzUnpackAction() {
    int [] result = new int[212];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\54\0\130\0\54\0\204\0\260\0\334\0\u0108"+
    "\0\u0134\0\u0160\0\u018c\0\u01b8\0\u01e4\0\u0210\0\u023c\0\u0268"+
    "\0\u0294\0\u02c0\0\u02ec\0\54\0\u0318\0\u0344\0\u0370\0\u039c"+
    "\0\54\0\54\0\54\0\54\0\54\0\54\0\54\0\54"+
    "\0\54\0\u03c8\0\u03f4\0\u0420\0\u044c\0\334\0\u0478\0\u04a4"+
    "\0\u04d0\0\u04fc\0\u0528\0\u0554\0\u0580\0\u05ac\0\u05d8\0\u0604"+
    "\0\u0630\0\u065c\0\u0688\0\u06b4\0\u06e0\0\u070c\0\u0738\0\u0764"+
    "\0\u0790\0\u07bc\0\u07e8\0\u0814\0\u0840\0\u086c\0\54\0\u0898"+
    "\0\u0420\0\54\0\u08c4\0\u08f0\0\u091c\0\u0948\0\u0974\0\u09a0"+
    "\0\u09cc\0\u09f8\0\u0a24\0\u0a50\0\u0a7c\0\u0aa8\0\u0ad4\0\u0b00"+
    "\0\u0b2c\0\u0b58\0\u0b84\0\u0bb0\0\u0bdc\0\u0c08\0\u0c34\0\u0c60"+
    "\0\u0c8c\0\u0cb8\0\u0ce4\0\u0d10\0\u0d3c\0\u0d68\0\u0d94\0\334"+
    "\0\u0dc0\0\u0dec\0\u0e18\0\u0e44\0\u0e70\0\u0e9c\0\u0ec8\0\u0ef4"+
    "\0\u0f20\0\u0f4c\0\u0f78\0\u0fa4\0\u0fd0\0\u0ffc\0\u1028\0\u1054"+
    "\0\u1080\0\u10ac\0\u10d8\0\u1104\0\u1130\0\u115c\0\u1188\0\334"+
    "\0\u11b4\0\u11e0\0\u120c\0\334\0\334\0\u1238\0\u1264\0\u1290"+
    "\0\u12bc\0\u12e8\0\u1314\0\u1340\0\u136c\0\u1398\0\u13c4\0\u13f0"+
    "\0\u141c\0\334\0\334\0\u1448\0\u1474\0\u14a0\0\u14cc\0\334"+
    "\0\334\0\u14f8\0\u1524\0\u1550\0\u157c\0\u15a8\0\u15d4\0\u1600"+
    "\0\u162c\0\u1658\0\u1684\0\u16b0\0\u16dc\0\u1708\0\u1734\0\u1760"+
    "\0\u178c\0\334\0\u17b8\0\u17e4\0\u1810\0\u183c\0\u1868\0\u1894"+
    "\0\334\0\334\0\u18c0\0\u18ec\0\u1918\0\u1944\0\334\0\u1970"+
    "\0\u199c\0\u19c8\0\334\0\334\0\u19f4\0\334\0\u1a20\0\u1a4c"+
    "\0\334\0\u1a78\0\u1aa4\0\u1ad0\0\u1afc\0\u1b28\0\334\0\u1b54"+
    "\0\334\0\54\0\334\0\334\0\u1b80\0\u1bac\0\u1bd8\0\u1c04"+
    "\0\u1c30\0\334\0\u1c5c\0\u1c88\0\u1cb4\0\334\0\u1ce0\0\u1d0c"+
    "\0\u1d38\0\334\0\u1d64\0\334";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[212];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\2\2\1\10"+
    "\1\11\1\12\1\13\2\7\1\14\1\15\1\16\1\7"+
    "\1\17\1\20\1\21\2\7\1\22\1\23\2\7\1\24"+
    "\1\25\1\26\2\7\1\27\1\30\1\31\1\32\1\33"+
    "\1\34\1\35\1\36\1\37\1\40\1\41\1\5\55\0"+
    "\1\42\1\43\54\0\1\5\47\0\1\5\4\0\1\6"+
    "\2\0\1\44\50\0\3\7\2\0\22\7\1\0\6\7"+
    "\12\0\3\45\1\0\50\45\4\0\3\7\2\0\1\7"+
    "\1\46\20\7\1\0\3\7\1\47\2\7\16\0\3\7"+
    "\2\0\3\7\1\50\16\7\1\0\6\7\16\0\3\7"+
    "\2\0\3\7\1\51\4\7\1\52\1\7\1\53\7\7"+
    "\1\0\6\7\16\0\3\7\2\0\21\7\1\54\1\0"+
    "\6\7\16\0\3\7\2\0\3\7\1\55\16\7\1\0"+
    "\6\7\16\0\3\7\2\0\10\7\1\56\11\7\1\0"+
    "\6\7\16\0\3\7\2\0\3\7\1\57\16\7\1\0"+
    "\6\7\16\0\3\7\2\0\11\7\1\60\2\7\1\61"+
    "\5\7\1\0\6\7\16\0\3\7\2\0\3\7\1\62"+
    "\1\7\1\63\4\7\1\64\1\7\1\65\5\7\1\0"+
    "\6\7\16\0\3\7\2\0\1\66\2\7\1\67\16\7"+
    "\1\0\6\7\16\0\3\7\2\0\1\70\11\7\1\71"+
    "\7\7\1\0\6\7\16\0\3\7\2\0\5\7\1\72"+
    "\4\7\1\73\7\7\1\0\6\7\16\0\3\7\2\0"+
    "\5\7\1\74\14\7\1\0\6\7\16\0\3\7\2\0"+
    "\5\7\1\75\14\7\1\0\6\7\16\0\3\7\2\0"+
    "\14\7\1\76\5\7\1\0\6\7\12\0\3\42\1\77"+
    "\50\42\2\100\1\0\51\100\4\0\1\101\47\0\10\45"+
    "\1\102\43\45\4\0\3\7\2\0\22\7\1\0\2\7"+
    "\1\103\3\7\16\0\3\7\2\0\10\7\1\104\11\7"+
    "\1\0\6\7\16\0\3\7\2\0\4\7\1\105\15\7"+
    "\1\0\6\7\16\0\3\7\2\0\14\7\1\106\5\7"+
    "\1\0\6\7\16\0\3\7\2\0\17\7\1\107\2\7"+
    "\1\0\6\7\16\0\3\7\2\0\12\7\1\110\7\7"+
    "\1\0\6\7\16\0\3\7\2\0\7\7\1\111\12\7"+
    "\1\0\6\7\16\0\3\7\2\0\14\7\1\112\5\7"+
    "\1\0\6\7\16\0\3\7\2\0\2\7\1\113\17\7"+
    "\1\0\6\7\16\0\3\7\2\0\1\114\21\7\1\0"+
    "\6\7\16\0\3\7\2\0\2\7\1\115\17\7\1\0"+
    "\6\7\16\0\3\7\2\0\6\7\1\116\13\7\1\0"+
    "\6\7\16\0\3\7\2\0\11\7\1\117\10\7\1\0"+
    "\6\7\16\0\3\7\2\0\21\7\1\120\1\0\6\7"+
    "\16\0\3\7\2\0\10\7\1\121\11\7\1\0\6\7"+
    "\16\0\3\7\2\0\15\7\1\122\4\7\1\0\6\7"+
    "\16\0\3\7\2\0\10\7\1\123\11\7\1\0\6\7"+
    "\16\0\3\7\2\0\6\7\1\124\13\7\1\0\6\7"+
    "\16\0\3\7\2\0\20\7\1\125\1\7\1\0\6\7"+
    "\16\0\3\7\2\0\6\7\1\126\1\7\1\127\11\7"+
    "\1\0\6\7\16\0\3\7\2\0\11\7\1\130\10\7"+
    "\1\0\6\7\16\0\3\7\2\0\10\7\1\131\11\7"+
    "\1\0\6\7\16\0\3\7\2\0\10\7\1\132\11\7"+
    "\1\0\6\7\16\0\3\7\2\0\15\7\1\133\4\7"+
    "\1\0\6\7\12\0\2\100\1\134\51\100\4\0\3\7"+
    "\2\0\14\7\1\135\5\7\1\0\6\7\16\0\3\7"+
    "\2\0\3\7\1\136\16\7\1\0\6\7\16\0\3\7"+
    "\2\0\2\7\1\137\17\7\1\0\6\7\16\0\3\7"+
    "\2\0\3\7\1\140\16\7\1\0\6\7\16\0\3\7"+
    "\2\0\2\7\1\141\17\7\1\0\6\7\16\0\3\7"+
    "\2\0\22\7\1\0\2\7\1\142\3\7\16\0\3\7"+
    "\2\0\10\7\1\143\11\7\1\0\6\7\16\0\3\7"+
    "\2\0\21\7\1\144\1\0\6\7\16\0\3\7\2\0"+
    "\10\7\1\145\11\7\1\0\6\7\16\0\3\7\2\0"+
    "\6\7\1\146\13\7\1\0\6\7\16\0\3\7\2\0"+
    "\5\7\1\147\14\7\1\0\6\7\16\0\3\7\2\0"+
    "\2\7\1\150\17\7\1\0\6\7\16\0\3\7\2\0"+
    "\5\7\1\151\14\7\1\0\6\7\16\0\3\7\2\0"+
    "\1\152\21\7\1\0\6\7\16\0\3\7\2\0\15\7"+
    "\1\153\4\7\1\0\6\7\16\0\3\7\2\0\1\154"+
    "\21\7\1\0\6\7\16\0\3\7\2\0\2\7\1\155"+
    "\17\7\1\0\6\7\16\0\3\7\2\0\14\7\1\156"+
    "\5\7\1\0\6\7\16\0\3\7\2\0\14\7\1\157"+
    "\5\7\1\0\6\7\16\0\3\7\2\0\1\7\1\160"+
    "\20\7\1\0\6\7\16\0\3\7\2\0\17\7\1\161"+
    "\2\7\1\0\6\7\16\0\3\7\2\0\15\7\1\162"+
    "\4\7\1\0\6\7\16\0\3\7\2\0\1\7\1\163"+
    "\20\7\1\0\6\7\16\0\3\7\2\0\1\164\21\7"+
    "\1\0\6\7\16\0\3\7\2\0\2\7\1\165\17\7"+
    "\1\0\6\7\13\0\1\77\56\0\3\7\2\0\1\166"+
    "\21\7\1\0\6\7\16\0\3\7\2\0\13\7\1\167"+
    "\6\7\1\0\6\7\16\0\3\7\2\0\5\7\1\170"+
    "\14\7\1\0\6\7\16\0\3\7\2\0\3\7\1\171"+
    "\16\7\1\0\6\7\16\0\3\7\2\0\14\7\1\172"+
    "\5\7\1\0\6\7\16\0\3\7\2\0\1\173\21\7"+
    "\1\0\6\7\16\0\3\7\2\0\5\7\1\174\14\7"+
    "\1\0\6\7\16\0\3\7\2\0\12\7\1\175\7\7"+
    "\1\0\6\7\16\0\3\7\2\0\3\7\1\176\16\7"+
    "\1\0\6\7\16\0\3\7\2\0\10\7\1\177\11\7"+
    "\1\0\6\7\16\0\3\7\2\0\10\7\1\200\11\7"+
    "\1\0\6\7\16\0\3\7\2\0\10\7\1\201\11\7"+
    "\1\0\6\7\16\0\3\7\2\0\2\7\1\202\17\7"+
    "\1\0\6\7\16\0\3\7\2\0\1\203\21\7\1\0"+
    "\6\7\16\0\3\7\2\0\22\7\1\0\1\7\1\204"+
    "\4\7\16\0\3\7\2\0\1\205\21\7\1\0\6\7"+
    "\16\0\3\7\2\0\15\7\1\206\4\7\1\0\6\7"+
    "\16\0\3\7\2\0\15\7\1\207\4\7\1\0\6\7"+
    "\16\0\3\7\2\0\5\7\1\210\14\7\1\0\6\7"+
    "\16\0\3\7\2\0\12\7\1\211\7\7\1\0\6\7"+
    "\16\0\3\7\2\0\3\7\1\212\16\7\1\0\6\7"+
    "\16\0\3\7\2\0\3\7\1\213\16\7\1\0\6\7"+
    "\16\0\3\7\2\0\22\7\1\0\3\7\1\214\2\7"+
    "\16\0\3\7\2\0\1\215\21\7\1\0\6\7\16\0"+
    "\3\7\2\0\3\7\1\216\16\7\1\0\6\7\16\0"+
    "\3\7\2\0\22\7\1\0\4\7\1\217\1\7\16\0"+
    "\3\7\2\0\4\7\1\220\15\7\1\0\6\7\16\0"+
    "\3\7\2\0\3\7\1\221\16\7\1\0\6\7\16\0"+
    "\3\7\2\0\11\7\1\222\10\7\1\0\6\7\16\0"+
    "\3\7\2\0\12\7\1\223\7\7\1\0\6\7\16\0"+
    "\3\7\2\0\3\7\1\224\16\7\1\0\6\7\16\0"+
    "\3\7\2\0\12\7\1\225\7\7\1\0\6\7\16\0"+
    "\3\7\2\0\2\7\1\226\17\7\1\0\6\7\16\0"+
    "\3\7\2\0\12\7\1\227\7\7\1\0\6\7\16\0"+
    "\3\7\2\0\16\7\1\230\3\7\1\0\6\7\16\0"+
    "\3\7\2\0\11\7\1\231\10\7\1\0\6\7\16\0"+
    "\3\7\2\0\13\7\1\232\6\7\1\0\6\7\16\0"+
    "\3\7\2\0\13\7\1\233\6\7\1\0\6\7\16\0"+
    "\3\7\2\0\13\7\1\234\6\7\1\0\6\7\16\0"+
    "\3\7\2\0\3\7\1\235\16\7\1\0\6\7\16\0"+
    "\3\7\2\0\2\7\1\236\17\7\1\0\6\7\16\0"+
    "\3\7\2\0\5\7\1\237\14\7\1\0\6\7\16\0"+
    "\3\7\2\0\22\7\1\0\1\240\5\7\16\0\3\7"+
    "\2\0\10\7\1\241\11\7\1\0\6\7\16\0\3\7"+
    "\2\0\12\7\1\242\7\7\1\0\6\7\16\0\3\7"+
    "\2\0\11\7\1\243\10\7\1\0\6\7\16\0\3\7"+
    "\2\0\1\7\1\244\20\7\1\0\6\7\16\0\3\7"+
    "\2\0\1\7\1\245\20\7\1\0\6\7\16\0\3\7"+
    "\2\0\1\7\1\246\20\7\1\0\6\7\16\0\3\7"+
    "\2\0\3\7\1\247\16\7\1\0\6\7\16\0\3\7"+
    "\2\0\11\7\1\250\10\7\1\0\6\7\16\0\3\7"+
    "\2\0\12\7\1\251\7\7\1\0\6\7\16\0\3\7"+
    "\2\0\3\7\1\252\16\7\1\0\6\7\16\0\3\7"+
    "\2\0\12\7\1\253\7\7\1\0\6\7\16\0\3\7"+
    "\2\0\14\7\1\254\5\7\1\0\6\7\16\0\3\7"+
    "\2\0\14\7\1\255\5\7\1\0\6\7\16\0\3\7"+
    "\2\0\11\7\1\256\10\7\1\0\6\7\16\0\3\7"+
    "\2\0\5\7\1\257\14\7\1\0\6\7\16\0\3\7"+
    "\2\0\6\7\1\260\13\7\1\0\6\7\16\0\3\7"+
    "\2\0\1\261\21\7\1\0\6\7\16\0\3\7\2\0"+
    "\1\7\1\262\20\7\1\0\6\7\16\0\3\7\2\0"+
    "\12\7\1\263\7\7\1\0\6\7\16\0\3\7\2\0"+
    "\5\7\1\264\14\7\1\0\6\7\16\0\3\7\2\0"+
    "\1\265\21\7\1\0\6\7\16\0\3\7\2\0\5\7"+
    "\1\266\14\7\1\0\6\7\16\0\3\7\2\0\4\7"+
    "\1\267\15\7\1\0\6\7\16\0\3\7\2\0\22\7"+
    "\1\270\6\7\16\0\3\7\2\0\11\7\1\271\10\7"+
    "\1\0\6\7\16\0\3\7\2\0\11\7\1\272\10\7"+
    "\1\0\6\7\16\0\3\7\2\0\11\7\1\273\10\7"+
    "\1\0\6\7\16\0\3\7\2\0\3\7\1\274\16\7"+
    "\1\0\6\7\16\0\3\7\2\0\2\7\1\275\17\7"+
    "\1\0\6\7\16\0\3\7\2\0\13\7\1\276\6\7"+
    "\1\0\6\7\16\0\3\7\2\0\12\7\1\277\7\7"+
    "\1\0\6\7\16\0\3\7\2\0\17\7\1\300\2\7"+
    "\1\0\6\7\16\0\3\7\2\0\2\7\1\301\17\7"+
    "\1\0\6\7\25\0\1\302\44\0\3\7\2\0\12\7"+
    "\1\303\7\7\1\0\6\7\16\0\3\7\2\0\12\7"+
    "\1\304\7\7\1\0\6\7\16\0\3\7\2\0\17\7"+
    "\1\305\2\7\1\0\6\7\16\0\3\7\2\0\12\7"+
    "\1\306\7\7\1\0\6\7\16\0\3\7\2\0\12\7"+
    "\1\307\7\7\1\0\6\7\16\0\3\7\2\0\3\7"+
    "\1\310\16\7\1\0\6\7\16\0\3\7\2\0\3\7"+
    "\1\311\16\7\1\0\6\7\16\0\3\7\2\0\11\7"+
    "\1\312\10\7\1\0\6\7\16\0\3\7\2\0\1\7"+
    "\1\313\20\7\1\0\6\7\16\0\3\7\2\0\6\7"+
    "\1\314\13\7\1\0\6\7\16\0\3\7\2\0\6\7"+
    "\1\315\13\7\1\0\6\7\16\0\3\7\2\0\5\7"+
    "\1\316\14\7\1\0\6\7\16\0\3\7\2\0\15\7"+
    "\1\317\4\7\1\0\6\7\16\0\3\7\2\0\2\7"+
    "\1\320\17\7\1\0\6\7\16\0\3\7\2\0\1\321"+
    "\21\7\1\0\6\7\16\0\3\7\2\0\5\7\1\322"+
    "\14\7\1\0\6\7\16\0\3\7\2\0\5\7\1\323"+
    "\14\7\1\0\6\7\16\0\3\7\2\0\6\7\1\324"+
    "\13\7\1\0\6\7\12\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[7568];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\1\11\17\1\1\11\4\1\11\11"+
    "\4\0\31\1\1\11\1\0\1\1\1\11\31\1\1\0"+
    "\133\1\1\0\11\1\1\11\22\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[212];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */

ListaErrores errores = ListaErrores.getListaerror();


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public AnalisisLex_CCSS(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public AnalisisLex_CCSS(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 174) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 6: 
          { System.out.println("Se reconocio identificador "+yytext());	
					return new Symbol(sym.iden,yychar,yyline, new String(yytext()));
          }
        case 46: break;
        case 14: 
          { System.out.println("Se reconocio signo "+yytext());	
					return new Symbol(sym.coma,yychar,yyline,yytext());
          }
        case 47: break;
        case 21: 
          { System.out.println("Se reconocio signo "+yytext());	
					return new Symbol(sym.rtrue,yychar,yyline,yytext());
          }
        case 48: break;
        case 1: 
          { System.out.println("Error lexico: "+yytext());
errores.agregarerror(new ER(yyline,yycolumn, yytext(), 1, ""
                                + "Caracter no conocido"));
          }
        case 49: break;
        case 7: 
          { System.out.println("Se reconocio signo "+yytext());	
					return new Symbol(sym.menos,yychar,yyline,yytext());
          }
        case 50: break;
        case 27: 
          { System.out.println("Se reconocio reservada "+yytext());	
					return new Symbol(sym.rtamtex,yychar,yyline,yytext());
          }
        case 51: break;
        case 11: 
          { System.out.println("Se reconocio signo "+yytext());	
					return new Symbol(sym.dpuntos,yychar,yyline,yytext());
          }
        case 52: break;
        case 24: 
          { System.out.println("Se reconocio reservada "+yytext());	
					return new Symbol(sym.rletra,yychar,yyline,yytext());
          }
        case 53: break;
        case 39: 
          { System.out.println("Se reconocio propiedad "+yytext());	
					return new Symbol(sym.rcapital,yychar,yyline,yytext());
          }
        case 54: break;
        case 32: 
          { System.out.println("Se reconocio reservada "+yytext());	
					return new Symbol(sym.rformato,yychar,yyline,yytext());
          }
        case 55: break;
        case 43: 
          { System.out.println("Se reconocio propiedad "+yytext());	
					return new Symbol(sym.rjustificado,yychar,yyline,yytext());
          }
        case 56: break;
        case 37: 
          { System.out.println("Se reconocio propiedad "+yytext());	
					return new Symbol(sym.rizquierda,yychar,yyline,yytext());
          }
        case 57: break;
        case 36: 
          { System.out.println("Se reconocio propiedad "+yytext());	
					return new Symbol(sym.rvertical,yychar,yyline,yytext());
          }
        case 58: break;
        case 20: 
          { System.out.println("Se reconocio cadena "+yytext());	
					return new Symbol(sym.cadena,yychar,yyline, yytext());
          }
        case 59: break;
        case 12: 
          { System.out.println("Se reconocio signo "+yytext());	
					return new Symbol(sym.igual,yychar,yyline,yytext());
          }
        case 60: break;
        case 45: 
          { System.out.println("Se reconocio propiedad "+yytext());	
					return new Symbol(sym.rautore,yychar,yyline,yytext());
          }
        case 61: break;
        case 35: 
          { System.out.println("Se reconocio propiedad "+yytext());	
					return new Symbol(sym.rcentrado,yychar,yyline,yytext());
          }
        case 62: break;
        case 38: 
          { System.out.println("Se reconocio reservada "+yytext());	
					return new Symbol(sym.rcolortext,yychar,yyline,yytext());
          }
        case 63: break;
        case 8: 
          { System.out.println("Se reconocio signo "+yytext());	
					return new Symbol(sym.acorche,yychar,yyline,yytext());
          }
        case 64: break;
        case 13: 
          { System.out.println("Se reconocio signo "+yytext());	
					return new Symbol(sym.pcoma,yychar,yyline,yytext());
          }
        case 65: break;
        case 28: 
          { System.out.println("Se reconocio reservada "+yytext());	
					return new Symbol(sym.ropaque,yychar,yyline,yytext());
          }
        case 66: break;
        case 40: 
          { System.out.println("Se reconocio reservada "+yytext());	
					return new Symbol(sym.rminuscula,yychar,yyline,yytext());
          }
        case 67: break;
        case 30: 
          { System.out.println("Se reconocio propiedad "+yytext());	
					return new Symbol(sym.rcursiva,yychar,yyline,yytext());
          }
        case 68: break;
        case 19: 
          { System.out.println("Se reconocio decimal "+yytext());	
					return new Symbol(sym.decimal,yychar,yyline, yytext());
          }
        case 69: break;
        case 23: 
          { System.out.println("Se reconocio reservada "+yytext());	
					return new Symbol(sym.rgrupo,yychar,yyline,yytext());
          }
        case 70: break;
        case 4: 
          { /* Se ignoran */ yychar = 0;
          }
        case 71: break;
        case 15: 
          { System.out.println("Se reconocio signo "+yytext());	
					return new Symbol(sym.aparen,yychar,yyline,yytext());
          }
        case 72: break;
        case 34: 
          { System.out.println("Se reconocio propiedad "+yytext());	
					return new Symbol(sym.ralineado,yychar,yyline,yytext());
          }
        case 73: break;
        case 26: 
          { System.out.println("Se reconocio reservada "+yytext());	
					return new Symbol(sym.rborde,yychar,yyline,yytext());
          }
        case 74: break;
        case 44: 
          { System.out.println("Se reconocio reservada "+yytext());	
					return new Symbol(sym.rfondoele,yychar,yyline,yytext());
          }
        case 75: break;
        case 17: 
          { System.out.println("Se reconocio reservada "+yytext());	
					return new Symbol(sym.rid,yychar,yyline,yytext());
          }
        case 76: break;
        case 29: 
          { System.out.println("Se reconocio propiedad "+yytext());	
					return new Symbol(sym.rderecha,yychar,yyline,yytext());
          }
        case 77: break;
        case 31: 
          { System.out.println("Se reconocio reservada "+yytext());	
					return new Symbol(sym.rvisible,yychar,yyline,yytext());
          }
        case 78: break;
        case 5: 
          { System.out.println("Se reconocio numero "+yytext());	
					return new Symbol(sym.num,yychar,yyline,yytext());
          }
        case 79: break;
        case 16: 
          { System.out.println("Se reconocio signo "+yytext());	
					return new Symbol(sym.cparen,yychar,yyline,yytext());
          }
        case 80: break;
        case 2: 
          { System.out.println("Se reconocio signo "+yytext());	
					return new Symbol(sym.div,yychar,yyline,yytext());
          }
        case 81: break;
        case 10: 
          { System.out.println("Se reconocio signo "+yytext());	
					return new Symbol(sym.mas,yychar,yyline,yytext());
          }
        case 82: break;
        case 18: 
          { /* Se ignoran */
          }
        case 83: break;
        case 42: 
          { System.out.println("Se reconocio propiedad "+yytext());	
					return new Symbol(sym.rhorizontal,yychar,yyline,yytext());
          }
        case 84: break;
        case 25: 
          { System.out.println("Se reconocio signo "+yytext());	
					return new Symbol(sym.rfalse,yychar,yyline,yytext());
          }
        case 85: break;
        case 22: 
          { System.out.println("Se reconocio reservada "+yytext());	
					return new Symbol(sym.rtexto,yychar,yyline,yytext());
          }
        case 86: break;
        case 41: 
          { System.out.println("Se reconocio reservada "+yytext());	
					return new Symbol(sym.rmayuscula,yychar,yyline,yytext());
          }
        case 87: break;
        case 3: 
          { System.out.println("Se reconocio signo "+yytext());	
					return new Symbol(sym.por,yychar,yyline,yytext());
          }
        case 88: break;
        case 33: 
          { System.out.println("Se reconocio reservada "+yytext());	
					return new Symbol(sym.rnegrilla,yychar,yyline,yytext());
          }
        case 89: break;
        case 9: 
          { System.out.println("Se reconocio signo "+yytext());	
					return new Symbol(sym.ccorche,yychar,yyline,yytext());
          }
        case 90: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
