
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Mar 09 22:58:35 CST 2018
//----------------------------------------------------

package Gramaticas.CSS;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int rvertical = 43;
  public static final int rletra = 10;
  public static final int rderecha = 20;
  public static final int rgrupo = 18;
  public static final int coma = 32;
  public static final int igual = 30;
  public static final int acorche = 23;
  public static final int ccorche = 24;
  public static final int dpuntos = 29;
  public static final int rcentrado = 21;
  public static final int rminuscula = 7;
  public static final int rvisible = 14;
  public static final int rhorizontal = 42;
  public static final int iden = 38;
  public static final int ropaque = 16;
  public static final int rcolortext = 17;
  public static final int rcapital = 8;
  public static final int menos = 25;
  public static final int rid = 2;
  public static final int EOF = 0;
  public static final int rizquierda = 19;
  public static final int mas = 26;
  public static final int error = 1;
  public static final int pcoma = 31;
  public static final int por = 27;
  public static final int rtexto = 3;
  public static final int rfalse = 36;
  public static final int rborde = 15;
  public static final int rtamtex = 11;
  public static final int rnegrilla = 4;
  public static final int rmayuscula = 6;
  public static final int rformato = 9;
  public static final int rfondoele = 12;
  public static final int rautore = 13;
  public static final int rjustificado = 22;
  public static final int rcursiva = 5;
  public static final int div = 28;
  public static final int aparen = 33;
  public static final int ralineado = 41;
  public static final int num = 37;
  public static final int cparen = 34;
  public static final int decimal = 40;
  public static final int rtrue = 35;
  public static final int cadena = 39;
}

