/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;
import Gramaticas.CHTML.*;
import Gramaticas.CJS.*;
import Gramaticas.CSS.*;
import EDD.CSJ.*;
import EDD.CSJ.Interprete.*;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.font.TextAttribute;
import java.io.BufferedReader;
import java.io.StringReader;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Hashtable;
import java.util.Locale;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.ScrollPaneConstants;
import javax.swing.border.LineBorder;
import javax.swing.text.StyledEditorKit;
/**
 *
 * @author danielvega
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtarea = new javax.swing.JTextArea();
        txtcompilar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        panelresultados = new javax.swing.JPanel();
        labelVar = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtarea.setColumns(20);
        txtarea.setRows(5);
        jScrollPane1.setViewportView(txtarea);

        txtcompilar.setText("CHTML");
        txtcompilar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcompilarActionPerformed(evt);
            }
        });

        jButton1.setText("CJS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("CSS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        panelresultados.setBackground(new java.awt.Color(174, 130, 130));
        panelresultados.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        labelVar.setFont(new java.awt.Font("DejaVu Sans Mono", 0, 12)); // NOI18N
        labelVar.setText("jLabel1");
        labelVar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelVarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelresultadosLayout = new javax.swing.GroupLayout(panelresultados);
        panelresultados.setLayout(panelresultadosLayout);
        panelresultadosLayout.setHorizontalGroup(
            panelresultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelresultadosLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(labelVar, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
        );
        panelresultadosLayout.setVerticalGroup(
            panelresultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelresultadosLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(labelVar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(276, Short.MAX_VALUE))
        );

        jButton3.setText("Pruebas");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(txtcompilar)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(49, 49, 49)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(panelresultados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelresultados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtcompilar)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    InterpreteCHTML aux=null;
    private void txtcompilarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcompilarActionPerformed
        // TODO add your handling code here:
         String input = txtarea.getText();
         AnalisisLex_CHTML lexico = new AnalisisLex_CHTML(new BufferedReader(new StringReader(input)));
         /*PantallaInicio ini = new PantallaInicio();
         ini.setVisible(true);*/
        //SE INICIALIZA EL ANALISIS SINTACTICO TOMA COMO PARAMETRO EL LEXICO
     /*  JFrame fr2 = new JFrame();
       fr2.setSize(500,500);               JLabel label = new JLabel();
       label.setSize(WIDTH, HEIGHT);
               Font f= new Font("Arial", Font.BOLD, 14); // Nombre, Estilo, Tamaño
label.setFont(f);
fr2.add(label);
                fr2.setVisible(true);*/
     int[ ] array = new int[4];
     array[0]=Font.ITALIC;
     array[1]=Font.BOLD;
     Font f= new Font("Calibri", array[1], 14); // Nombre, Estilo, Tamaño
     Map<TextAttribute, Integer> fontAttributes = new HashMap<>();
fontAttributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
Font boldUnderline = new Font("Serif",Font.BOLD, 12).deriveFont(fontAttributes);
this.labelVar.setFont(boldUnderline);
this.labelVar.setText("<html><body><span style='text-decoration: line-through;'>Text Here</span></body></html>");
        System.out.println(factorialactualizado(3));
      /*  Object g = 1;
        if(g instanceof  Integer){
            System.out.println("Si se puede castear");
        }else{
            System.out.println("no se puede");
        }*/
/*float h = (float) Math.random();
        System.out.println(h);*/
        /*int val = "Hola".compareTo("HolA");
        if(val<0){
            System.out.println("True");
        }else{
            System.out.println("false");
        }  */
       // System.out.println("Hola".compareTo("HolA") < 0);
/*LineBorder line = new LineBorder(Color.yellow, 15, true);

    this.panelresultados.setBorder(line);*/
/*Integer outputDecimal = Integer.parseInt("6365ff", 16);
        System.out.println(outputDecimal);*/
   

     /*Font font = this.hola.getFont();
     
      Hashtable<TextAttribute, Object> map =
            new Hashtable<>();
 
      map.put(TextAttribute.FONT, f);
      map.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
      
      font = font.deriveFont(map);
      this.hola.setFont(font);*/
      /*  System.out.println(array[0]);
        System.out.println(array[1]);*/
      
    
/*this.hola.setFont(f);
 this.hola.setFont(h);*/
        SintacticoCHTML sintactico = new SintacticoCHTML(lexico);
        try {

            //SE INICIA LA COMPILACION LEXICO Y SINTACTICO
            sintactico.parse();
            
            ArbolCSJ raiz = sintactico.arbol;
            
            if(raiz!=null){
              //  System.out.println(raiz.getRaiz().hashCode());
                GraficarArbol grafo = new GraficarArbol();
                grafo.recorrrerarbol(raiz.getRaiz(), 0);
                grafo.contador=0;
                grafo.enlazararbol(raiz.getRaiz(), 0);
                grafo.graficar(grafo.auxdot,"chtml.png");
                InterpreteCHTML chtml = new InterpreteCHTML(new Pagina());
                chtml.ejecutarchtml(raiz.getRaiz(), "global");
                /*this.panelresultados.setLayout(new FlowLayout(FlowLayout.CENTER));
                this.panelresultados.add(chtml.getTxt());
                this.panelresultados.add(chtml.getBtn());
                this.panelresultados.validate();*/
                //this.panelresultados = new JPanel();
                /*this.panelresultados.add(chtml.getPanel());
                this.panelresultados.validate();*/   
                JFrame frame2 = new JFrame();
                JPanel pn = chtml.getPanel();
                pn.validate();
                chtml.actur=true;
                JScrollPane scrollPane = new JScrollPane(pn, ScrollPaneConstants.VERTICAL_SCROLLBAR_AS_NEEDED, ScrollPaneConstants.HORIZONTAL_SCROLLBAR_AS_NEEDED);
                frame2.add(scrollPane);
                frame2.setSize(800,800);
                frame2.setVisible(true);
                chtml.settearaccion(false);
                aux=chtml;
               // System.out.println(chtml.comandoactual);
                /*this.add(chtml.getPanel());
                this.pack();
                this.repaint();*/
                
                /*JFrame fr = chtml.getFrame();
                fr.pack();
                fr.setVisible(true);*/
                
       
            }
        } catch (Exception ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtcompilarActionPerformed

    private int factorialactualizado(int num){
        /*
        funcion factorial(num){
	si(num <= 0){
		retornar 1;
	}sino{
		retornar num*factorial(num-2) * num*factorial(num - 1); 
	}
}
        */
        if(num<=0){
            return 1;
        }else{
            return num*factorialactualizado(num-2) * num*factorialactualizado(num-1);
        }
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String input = txtarea.getText();
         AnalisisLex_CJS lexico = new AnalisisLex_CJS(new BufferedReader(new StringReader(input)));
        //SE INICIALIZA EL ANALISIS SINTACTICO TOMA COMO PARAMETRO EL LEXICO
       
        SintacticoCJS sintactico = new SintacticoCJS(lexico);
        try {

            //SE INICIA LA COMPILACION LEXICO Y SINTACTICO
            sintactico.parse();
            ArbolCSJ raiz = sintactico.arbol;
            if(raiz!=null){
              //  System.out.println(raiz.getRaiz().hashCode());
                GraficarArbol grafo = new GraficarArbol();
                grafo.recorrrerarbol(raiz.getRaiz(), 0);
                grafo.contador=0;
                grafo.enlazararbol(raiz.getRaiz(), 0);
                grafo.graficar(grafo.auxdot,"cjs.png");
                InterpreteCSJ csj = new InterpreteCSJ();
                csj.verificarerroresPrecompilacion(raiz.getRaiz(), "global");
                csj.errores.recorrerErrores();
                //csj.llenarTablaSimbolos(raiz.getRaiz(), "global");
                csj.llenarMetodos(raiz.getRaiz(), "global");
                csj.llenarTablaSimbolos(raiz.getRaiz(), "global");
                csj.errores.recorrerErrores();
                //csj.ejecutarArbol(raiz.getRaiz(), "global");
            }
            //System.out.println("Todo bien");
            /*if(sintactico.arbol!=null){
                ArbolAST aux = sintactico.arbol;
                if(aux!=null){
                    Interprete.HASKELL.Interprete inter = new Interprete.HASKELL.Interprete();
                    inter.llenartablaSimbolos(aux.getRaiz(),"global");
                    this.hsk = inter;
                   }
            }
        
            auxsin=sintactico;*/
        } catch (Exception ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         String input = txtarea.getText();
         AnalisisLex_CCSS lexico = new AnalisisLex_CCSS(new BufferedReader(new StringReader(input)));
        //SE INICIALIZA EL ANALISIS SINTACTICO TOMA COMO PARAMETRO EL LEXICO
       
        SintacticoCCSS sintactico = new SintacticoCCSS(lexico);
        try {

            //SE INICIA LA COMPILACION LEXICO Y SINTACTICO
            sintactico.parse();
            ArbolCSJ raiz = sintactico.arbol;
            if(raiz!=null){
              //  System.out.println(raiz.getRaiz().hashCode());
                GraficarArbol grafo = new GraficarArbol();
                grafo.recorrrerarbol(raiz.getRaiz(), 0);
                grafo.contador=0;
                grafo.enlazararbol(raiz.getRaiz(), 0);
                grafo.graficar(grafo.auxdot,"css.png");
                InterpreteCSS css = new InterpreteCSS();
                css.ejecutarCSS(raiz.getRaiz());
                /*String pal1 = "hola2", pal2= "hola";
                int compareTo = pal1.compareTo(pal2);
                System.out.println(compareTo);*/
                /*InterpreteCSJ csj = new InterpreteCSJ();
                csj.llenarTablaSimbolos(raiz.getRaiz(), "global");*/
            }
        } catch (Exception ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        aux.actualizarPanel();
        try {            // TODO add your handling code here:
            //HH:mm:ss
            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy", Locale.getDefault());
            SimpleDateFormat formato2 = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss", Locale.getDefault());
            //String valprueba ="01/02/2017";
            formato.setLenient(false);
            Date date1 = formato.parse("01/02/2017");
            Date date2 = formato2.parse("01/02/2017 23:59:59");
            int v = date1.compareTo(date2);
            System.out.println(v);
            
        } catch (ParseException ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void labelVarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelVarMouseClicked
        // TODO add your handling code here:
        System.out.println("hola");
    }//GEN-LAST:event_labelVarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelVar;
    private javax.swing.JPanel panelresultados;
    private javax.swing.JTextArea txtarea;
    private javax.swing.JButton txtcompilar;
    // End of variables declaration//GEN-END:variables
}
